/* ------------------------------------------------------------------ */
/*  Database types                                                     */
/*                                                                     */
/*  The canonical `Database` type and all Row / Insert / Update /      */
/*  Enum helpers are AUTO-GENERATED by `supabase gen types`.           */
/*                                                                     */
/*  Regenerate:  npx supabase gen types typescript --local \           */
/*               | Out-File -Encoding utf8 src/lib/types/database.generated.ts */
/*                                                                     */
/*  This file provides:                                                */
/*    1. Re-exports of generated helpers (Database, Tables, etc.)      */
/*    2. Short convenience aliases (OrderRow, ProductRow, …)           */
/*    3. JSONB shape types for casting (AddressJson, PlanFeaturesJson) */
/*    4. Enriched/join types not in the DB (ReviewWithUser, etc.)      */
/* ------------------------------------------------------------------ */

// ── Re-exports from generated file ────────────────────────────────

export type {
  Database,
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
} from "@/lib/types/database.generated";

import type { Tables, TablesInsert, TablesUpdate, Enums } from "@/lib/types/database.generated";

// ── Enum convenience aliases ──────────────────────────────────────
// These resolve to the union literal types generated from PG enums.

export type AppRole = Enums<"app_role">;
export type OrderStatus = Enums<"order_status">;
export type SubscriberStatus = Enums<"subscriber_status">;
export type SubscriptionStatus = Enums<"subscription_status">;
export type PaymentMethod = Enums<"payment_method">;
export type DiscountType = Enums<"discount_type">;
export type ReviewStatus = Enums<"review_status">;
export type InvoiceStatus = Enums<"invoice_status">;
export type BillingCycle = Enums<"billing_cycle">;

/** Event types for subscription_payment_events (check constraint in DB) */
export type SubscriptionPaymentEventType =
  | "checkout_started"
  | "checkout_succeeded"
  | "checkout_failed"
  | "renewal_started"
  | "renewal_succeeded"
  | "renewal_failed"
  | "cancellation_requested"
  | "subscription_suspended"
  | "subscription_reactivated"
  | "plan_changed"
  | "token_updated";

// ── Table Row aliases ─────────────────────────────────────────────

export type ProfileRow = Tables<"profiles">;
export type CategoryRow = Tables<"categories">;
export type ProductRow = Tables<"products">;
export type ProductVariantRow = Tables<"product_variants">;
export type ProductCategoryRow = Tables<"product_categories">;
export type CouponRow = Tables<"coupons">;
export type OrderRow = Tables<"orders">;
export type OrderItemRow = Tables<"order_items">;
export type OrderNoteRow = Tables<"order_notes">;
export type SubscriberRow = Tables<"subscribers">;
export type AuditLogRow = Tables<"audit_logs">;
export type ShopPageRow = Tables<"shop_pages">;
export type ProductExtraRow = Tables<"product_extras">;
export type PriceHistoryRow = Tables<"price_history">;
export type ShopPlanRow = Tables<"shop_plans">;
export type ShopSubscriptionRow = Tables<"shop_subscriptions">;
export type SubscriptionInvoiceRow = Tables<"subscription_invoices">;
export type PostRow = Tables<"posts">;
export type ReviewRow = Tables<"reviews">;
export type SubscriptionPaymentEventRow = Tables<"subscription_payment_events">;

// ── Table Insert aliases ──────────────────────────────────────────

export type ProfileInsert = TablesInsert<"profiles">;
export type CategoryInsert = TablesInsert<"categories">;
export type ProductInsert = TablesInsert<"products">;
export type ProductVariantInsert = TablesInsert<"product_variants">;
export type ProductCategoryInsert = TablesInsert<"product_categories">;
export type CouponInsert = TablesInsert<"coupons">;
export type OrderInsert = TablesInsert<"orders">;
export type OrderItemInsert = TablesInsert<"order_items">;
export type OrderNoteInsert = TablesInsert<"order_notes">;
export type SubscriberInsert = TablesInsert<"subscribers">;
export type AuditLogInsert = TablesInsert<"audit_logs">;
export type ShopPageInsert = TablesInsert<"shop_pages">;
export type ProductExtraInsert = TablesInsert<"product_extras">;
export type PriceHistoryInsert = TablesInsert<"price_history">;
export type ShopPlanInsert = TablesInsert<"shop_plans">;
export type ShopSubscriptionInsert = TablesInsert<"shop_subscriptions">;
export type SubscriptionInvoiceInsert = TablesInsert<"subscription_invoices">;
export type PostInsert = TablesInsert<"posts">;
export type ReviewInsert = TablesInsert<"reviews">;
export type SubscriptionPaymentEventInsert = TablesInsert<"subscription_payment_events">;

// ── Table Update aliases ──────────────────────────────────────────

export type ProfileUpdate = TablesInsert<"profiles">;
export type CategoryUpdate = TablesUpdate<"categories">;
export type ProductUpdate = TablesUpdate<"products">;
export type ProductVariantUpdate = TablesUpdate<"product_variants">;
export type ProductCategoryUpdate = TablesUpdate<"product_categories">;
export type CouponUpdate = TablesUpdate<"coupons">;
export type OrderUpdate = TablesUpdate<"orders">;
export type OrderItemUpdate = TablesUpdate<"order_items">;
export type SubscriberUpdate = TablesUpdate<"subscribers">;
export type AuditLogUpdate = TablesUpdate<"audit_logs">;
export type ShopPageUpdate = TablesUpdate<"shop_pages">;
export type ShopPlanUpdate = TablesUpdate<"shop_plans">;
export type ShopSubscriptionUpdate = TablesUpdate<"shop_subscriptions">;
export type SubscriptionInvoiceUpdate = TablesUpdate<"subscription_invoices">;
export type PostUpdate = TablesUpdate<"posts">;
export type ReviewUpdate = TablesUpdate<"reviews">;
export type SubscriptionPaymentEventUpdate = TablesUpdate<"subscription_payment_events">;

// ── View Row aliases ──────────────────────────────────────────────

export type ReviewStatsRow = Tables<"product_review_stats">;

// ── JSONB shape types (for casting at point of use) ───────────────
// These columns are stored as `jsonb` in the DB and generated as `Json`.
// Use these types when you need to access specific fields after reading.

export type AddressJson = {
  name: string;
  street: string;
  city: string;
  zip: string;
  country: string;
};

export type BillingAddressJson = AddressJson & {
  company_name?: string;
  tax_number?: string;
};

export type PickupPointJson = {
  provider?: string;
  point_id?: string;
  point_label?: string;
};

export type VariantSnapshotJson = {
  option1Name?: string;
  option1Value?: string;
  option2Name?: string;
  option2Value?: string;
  sku?: string;
};

/** Shape of the features JSONB column in shop_plans / feature_overrides in shop_subscriptions */
export type PlanFeaturesJson = {
  max_products: number;
  max_admins: number;
  max_categories: number;
  delivery_options: number;
  enable_coupons: boolean;
  enable_marketing_module: boolean;
  enable_abandoned_cart: boolean;
  enable_b2b_wholesale: boolean;
  enable_reviews: boolean;
  enable_price_history: boolean;
  enable_product_extras: boolean;
  enable_scheduled_publishing: boolean;
  enable_agency_viewer: boolean;
  enable_custom_pages: boolean;
  enable_blog: boolean;
};

// ── Structured content types for CMS pages (FE-023) ───────────────

export type AboutUsHeroSection = {
  title: string;
  subtitle: string;
  imageUrl: string | null;
};

export type AboutUsStorySection = {
  title: string;
  body: string;
};

export type AboutUsTeamMember = {
  name: string;
  role: string;
  imageUrl: string | null;
  bio: string;
};

export type AboutUsValue = {
  title: string;
  description: string;
  icon: string;
};

export type AboutUsContactSection = {
  address: string;
  phone: string;
  email: string;
  mapEmbedUrl: string | null;
};

export type AboutUsContent = {
  hero: AboutUsHeroSection;
  story: AboutUsStorySection;
  team: AboutUsTeamMember[];
  values: AboutUsValue[];
  contact: AboutUsContactSection;
};

// ── Enriched / join types (not in DB, assembled in server actions) ─

/** OrderNote with resolved author name for display */
export type OrderNoteWithAuthor = OrderNoteRow & {
  author_name: string | null;
};

/** Extra row enriched with the extra product's live price and stock info */
export type ProductExtraWithProduct = ProductExtraRow & {
  extra_product_title: string;
  extra_product_slug: string;
  extra_product_price: number;
  extra_product_image: string | null;
  extra_product_is_active: boolean;
  extra_variant_price: number | null;
  extra_variant_stock: number | null;
  extra_variant_is_active: boolean | null;
};

/** Subscription enriched with its associated plan for display */
export type ShopSubscriptionWithPlan = ShopSubscriptionRow & {
  plan: ShopPlanRow;
};

/** Review enriched with author name for storefront display */
export type ReviewWithUser = ReviewRow & {
  author_name: string | null;
};

/** Review enriched with product info for admin moderation list */
export type ReviewWithProduct = ReviewRow & {
  product_title: string;
  product_slug: string;
  product_main_image_url: string | null;
  author_name: string | null;
};

/** Aggregated review statistics for a product (from product_review_stats view) */
export type ReviewStats = {
  product_id: string;
  review_count: number;
  average_rating: number;
  five_star: number;
  four_star: number;
  three_star: number;
  two_star: number;
  one_star: number;
};

/** Post summary for public blog list */
export type PostSummary = Pick<
  PostRow,
  "id" | "slug" | "title" | "excerpt" | "cover_image_url" | "published_at" | "tags"
> & {
  author_name: string | null;
};

/** Full post detail for public single post page */
export type PostDetail = PostRow & {
  author_name: string | null;
};

/** Post row enriched for admin list */
export type PostAdmin = PostRow & {
  author_name: string | null;
};
